# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6190f78b0898427d1f9b2ccab0c1496af24a0f46d21116c6fd4f383db076d63ce3e1e3bb5c60c0f3ea8d856b43d0f6dd6d504b4767dea1f98afc9334c22d4f97

test:
  secret_key_base: 4de4a8f32f718c4f8a1babb7059994dc040568fbe0079b2f5572a2b7eeee6b3ea9f160af36e535ef7163ddc425fc6ef4f1d9dba082dc300df82f4207ed063b0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
